version: '2'

services:
  uaa-server:
    build: uaa/
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,postgresql

  uaa-db:
    image: postgres:9.6.3
    ports:
      - "5432:5432"