version: '2'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server
    env_file:
      - env_vars
    ports:
      - "8888:8888"

  service-discovery:
    image: nimbleplatform/service-discovery
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  gateway-proxy:
    image: nimbleplatform/gateway-proxy
    env_file:
      - env_vars
    ports:
      - "8080:80"
    depends_on:
      - config-server
      - service-discovery

  hystrix-dashboard:
    image: nimbleplatform/hystrix-dashboard
    env_file:
      - env_vars
    ports:
      - "9080:9080"
    depends_on:
      - config-server
      - service-discovery