version: '3'

services:
  keycloak:
     image: jboss/keycloak:3.4.0.Final
     env_file:
       - keycloak_default_env
       - keycloak_secrets
    environment:
      - PROXY_ADDRESS_FORWARDING=true
     links:
       - keycloak-db:postgres
     ports:
       - "10096:8080"
       - "9999:9990"
       - "8088:8443"
     depends_on:
       - keycloak-db
     networks:
       - nimble-cloud-infra

  keycloak-db:
    image: postgres:9.6.3
    env_file:
      - keycloak_default_env
      - keycloak_secrets