version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:latest
    env_file:
      - env_vars
      - env_vars-prod
    environment:
      - POSTGRES_HOST=sl-eu-lon-2-portal.5.dblayer.com
      - POSTGRES_PORT=21113
      - POSTGRES_DB=identitydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${IDENTITY_DB_PASSWORD}
    ports:
      - "9096:9096"
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:latest
    env_file:
      - env_vars
      - env_vars-prod
    environment:
      - BUSINESS_PROCESS_DB_HOST=sl-eu-lon-2-portal.5.dblayer.com
      - BUSINESS_PROCESS_DB_PORT=21113
      - BUSINESS_PROCESS_DB_NAME=businessprocessdb
      - BUSINESS_PROCESS_DB_USERNAME=admin
      - BUSINESS_PROCESS_DB_PASSWORD=${BUSINESS_PROCESS_DB_PASSWORD}
      - CAMUNDA_DB_HOST=sl-eu-lon-2-portal.5.dblayer.com
      - CAMUNDA_DB_PORT=21113
      - CAMUNDA_DB_NAME=camundadb
      - CAMUNDA_DB_USERNAME=admin
      - CAMUNDA_DB_PASSWORD=${CAMUNDA_DB_PASSWORD}
    ports:
      - "8085:8085"
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service:latest
    ports:
      - "10095:8095"
    env_file:
      - env_vars
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:latest
    ports:
      - "9092:8080"
    env_file:
      - env_vars
      - env_vars-prod
    networks:
      - infra
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-prod
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfraprod_default