version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################

  identity-service:
    image: nimbleplatform/identity-service:latest
    env_file:
      - env_vars
    environment:
      - IDENTIY_DB_URI=identity-service-db:5432
    ports:
      - "9096:9096"
    networks:
      - infra
      - identity-backend
    depends_on:
      - identity-service-db

  identity-service-db:
    image: postgres:9.6.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=identityDB
    networks:
      - identity-backend

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:latest
    env_file:
      - env_vars
    environment:
      - BUSINESS_PROCESS_DB_URI=business-process-service-db:5432
    ports:
      - "8085:8085"
    networks:
      - infra
      - business-process-backend
    depends_on:
      - business-process-service-db

  business-process-service-db:
    image: postgres:9.6.3
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=camunda
    networks:
      - business-process-backend

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service-micro-srdc:latest
    ports:
      - "10095:8095"
    env_file:
      - env_vars
    networks:
      - infra
      - catalog-backend

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:latest
    ports:
      - "9092:8080"
    env_file:
      - env_vars
    networks:
      - infra
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfra_default
  identity-backend:
  catalog-backend:
  business-process-backend: