version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nimble-platform.salzburgresearch.at.chained.crt:/etc/nginx/nimble-platform.salzburgresearch.at.chained.crt:ro
      - ./nimble-platform.salzburgresearch.at.key:/etc/nginx/nimble-platform.salzburgresearch.at.key:ro
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - nimble-cloud-infra
#      - jenkins


networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfraprod_default
#  jenkins:
#    external:
#      name: jenkins_default