version: '2'

services:
  jenkins_master:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
