version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:staging
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - POSTGRES_HOST=sl-eu-lon-2-portal.1.dblayer.com
      - POSTGRES_PORT=21736
      - POSTGRES_DB=identitydb
      - POSTGRES_USER=admin
    ports:
      - "9096:9096"
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:staging
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      - BUSINESS_PROCESS_DB_HOST=sl-eu-lon-2-portal.1.dblayer.com
      - BUSINESS_PROCESS_DB_PORT=21736
      - BUSINESS_PROCESS_DB_NAME=businessprocessdb
      - BUSINESS_PROCESS_DB_USERNAME=admin
      - CAMUNDA_DB_HOST=sl-eu-lon-2-portal.1.dblayer.com
      - CAMUNDA_DB_PORT=21736
      - CAMUNDA_DB_NAME=camundadb
      - CAMUNDA_DB_USERNAME=admin
    ports:
      - "8085:8085"
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service-micro:staging
    ports:
      - "10095:8095"
    env_file:
      - env_vars
      - env_vars-staging
    networks:
      - infra

  ##############################
  ####### Search Service ######
  ##############################

  search-service:
    image: nimbleplatform/catalog-search-service:staging
    ports:
      - "10096:8443"
    env_file:
      - env_vars
    environment:
      - "SPRING_PROFILES_ACTIVE=productive"
      - "MARMOTTA_URL=https://nimble-platform.salzburgresearch.at/marmotta"
      - "LANGUAGE_LABEL=http://www.w3.org/2004/02/skos/core#prefLabel"
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:staging
    ports:
      - "8081:8080"
    env_file:
      - env_vars
      - env_vars-staging
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-staging
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfrastaging_default