version: '2'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    ports:
      - "8888:8888"
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m

  service-discovery:
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m

  gateway-proxy:
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
    ports:
      - "80:80"
    depends_on:
      - config-server
      - service-discovery
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m

  ##########################
  ######## Keycloak ########
  ##########################

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    env_file:
      - keycloak/keycloak_default_env
      - keycloak/keycloak_secrets
    links:
      - keycloak-db:postgres
    ports:
      - "8080:8080"
      # - "9999:9999" # keycloak federation port - not used in local dev setup
      - "8443:8443"
    volumes:
      - ./data:/data
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:9.6.3
    env_file:
      - keycloak/keycloak_default_env
      - keycloak/keycloak_secrets
