version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    expose:
      - "8080"
    ports:
      - "443:80"
    networks:
      - nimble-cloud-infra
      - jenkins


networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfrastaging_default
  jenkins:
    external:
      name: jenkins_default